# ワークフロー名
name: housework_bot
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 11 * * *'

jobs:
  merge-release-changes:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout (GitHub)
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
            token: ${{ secrets.WORKFLOW_TOKEN }}
        - name: Commit changes
          run: |
            git config --global user.email "example.com"
            git config --global user.name "GitHub Actions test"
            git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Automated fixes by GitHub Actions" && git pull --rebase && git push origin HEAD:${{ github.head_ref }})

