# ワークフロー名
name: housework_bot
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 11 * * *'

jobs:
  merge-release-changes:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout (GitHub)
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # これが必要
        - name: Commit changes and merge(リリースブランチで行った変更をdevelop, mainへマージ)
          run: |
            git merge develop
