# ワークフロー名
name: housework_bot
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 11 * * *'

jobs:
  merge-release-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Show current datetime
        run: echo ${{ env.CURRENT_DATETIME }}
      - name: Commit changes
        run: |
            cp tmp/KJ.html docs/agent/KJ.html
            cp tmp/NT.html docs/agent/NT.html
            cp tmp/HK.html docs/agent/HK.html
            cp tmp/MF.html docs/agent/MF.html
            cp tmp/SY.html docs/agent/SY.html
            cp tmp/TT.html docs/agent/TT.html
            cp tmp/TY.html docs/agent/TY.html
            cp tmp/YS.html docs/agent/YS.html
            git add .
            git config --global user.email "example.com"
            git config --global user.name "GitHub Actions test"
            git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Check at ${{ env.CURRENT_DATETIME }}" && git pull --rebase && git push
            
